-- written by ckaotik
local MAJOR, MINOR = 'LibItemTokens', 1
assert(LibStub, MAJOR..' requires LibStub')
local lib, oldminor = LibStub:NewLibrary(MAJOR, MINOR)
if not lib then return end

local tokenData = setmetatable({}, {
	__index = function(self, itemID)
		local info = rawget(self, itemID)
		if type(info) == 'string' then
			-- convert to table
			local equipSlot, iLevel, items = strsplit(',', info, 3)
			info = {
				slot   = equipSlot,
				iLevel = tonumber(iLevel),
				items  = items, -- keep as a string (for now)
			}
			rawset(self, itemID, info)
		end
		return info
	end
})

function lib:IsToken(itemID)
	if rawget(tokenData, itemID) then return true end
end

function lib:GetTokenInfo(item)
	local itemID = type(item) == 'string' and (item:match('item:(%d+)') or '0')*1 or item
	if not lib:IsToken(itemID) then return end
	local info = tokenData[itemID]
	local _, _, quality, iLevel, level = GetItemInfo(item)
	return quality, info.iLevel or iLevel, level, info.equipSlot, info.items
end

do
	-- add data below
	tokenData[99712] = '' -- Leggings of the Cursed Conqueror
	tokenData[99713] = '' -- Leggings of the Cursed Protector
	tokenData[99714] = '' -- Chest of the Cursed Vanquisher
	tokenData[99715] = '' -- Chest of the Cursed Conqueror
	tokenData[99716] = '' -- Chest of the Cursed Protector
	tokenData[99717] = '' -- Shoulders of the Cursed Vanquisher
	tokenData[99718] = '' -- Shoulders of the Cursed Conqueror
	tokenData[99719] = '' -- Shoulders of the Cursed Protector
	tokenData[99720] = '' -- Gauntlets of the Cursed Vanquisher
	tokenData[99721] = '' -- Gauntlets of the Cursed Conqueror
	tokenData[99722] = '' -- Gauntlets of the Cursed Protector
	tokenData[99723] = '' -- Helm of the Cursed Vanquisher
	tokenData[99724] = '' -- Helm of the Cursed Conqueror
	tokenData[99725] = '' -- Helm of the Cursed Protector
	tokenData[99726] = '' -- Leggings of the Cursed Vanquisher
	tokenData[105866] = '' -- Essence of the Cursed Protector
	tokenData[105867] = '' -- Essence of the Cursed Conqueror
	tokenData[105868] = '' -- Essence of the Cursed Vanquisher
	tokenData[99682] = '' -- Gauntlets of the Cursed Vanquisher
	tokenData[99683] = '' -- Helm of the Cursed Vanquisher
	tokenData[99684] = '' -- Leggings of the Cursed Vanquisher
	tokenData[99685] = '' -- Shoulders of the Cursed Vanquisher
	tokenData[99686] = '' -- Chest of the Cursed Conqueror
	tokenData[99687] = '' -- Gauntlets of the Cursed Conqueror
	tokenData[99688] = '' -- Leggings of the Cursed Conqueror
	tokenData[99689] = '' -- Helm of the Cursed Conqueror
	tokenData[99690] = '' -- Shoulders of the Cursed Conqueror
	tokenData[99691] = '' -- Chest of the Cursed Protector
	tokenData[99692] = '' -- Gauntlets of the Cursed Protector
	tokenData[99693] = '' -- Leggings of the Cursed Protector
	tokenData[99694] = '' -- Helm of the Cursed Protector
	tokenData[99695] = '' -- Shoulders of the Cursed Protector
	tokenData[99696] = '' -- Chest of the Cursed Vanquisher
	tokenData[105857] = '' -- Essence of the Cursed Protector
	tokenData[105858] = '' -- Essence of the Cursed Conqueror
	tokenData[105859] = '' -- Essence of the Cursed Vanquisher
	tokenData[99742] = '' -- Chest of the Cursed Vanquisher
	tokenData[99743] = '' -- Chest of the Cursed Conqueror
	tokenData[99744] = '' -- Chest of the Cursed Protector
	tokenData[99745] = '' -- Gauntlets of the Cursed Vanquisher
	tokenData[99746] = '' -- Gauntlets of the Cursed Conqueror
	tokenData[99747] = '' -- Gauntlets of the Cursed Protector
	tokenData[99748] = '' -- Helm of the Cursed Vanquisher
	tokenData[99749] = '' -- Helm of the Cursed Conqueror
	tokenData[99750] = '' -- Helm of the Cursed Protector
	tokenData[99751] = '' -- Leggings of the Cursed Vanquisher
	tokenData[99752] = '' -- Leggings of the Cursed Conqueror
	tokenData[99753] = '' -- Leggings of the Cursed Protector
	tokenData[99754] = '' -- Shoulders of the Cursed Vanquisher
	tokenData[99755] = '' -- Shoulders of the Cursed Conqueror
	tokenData[99756] = '' -- Shoulders of the Cursed Protector
	tokenData[105863] = '' -- Essence of the Cursed Protector
	tokenData[105864] = '' -- Essence of the Cursed Conqueror
	tokenData[105865] = '' -- Essence of the Cursed Vanquisher
	tokenData[96566] = '' -- Chest of the Crackling Vanquisher
	tokenData[96567] = '' -- Chest of the Crackling Conqueror
	tokenData[96568] = '' -- Chest of the Crackling Protector
	tokenData[96599] = '' -- Gauntlets of the Crackling Vanquisher
	tokenData[96600] = '' -- Gauntlets of the Crackling Conqueror
	tokenData[96601] = '' -- Gauntlets of the Crackling Protector
	tokenData[96623] = '' -- Helm of the Crackling Vanquisher
	tokenData[96624] = '' -- Helm of the Crackling Conqueror
	tokenData[96625] = '' -- Helm of the Crackling Protector
	tokenData[96631] = '' -- Leggings of the Crackling Vanquisher
	tokenData[96632] = '' -- Leggings of the Crackling Conqueror
	tokenData[96633] = '' -- Leggings of the Crackling Protector
	tokenData[96699] = '' -- Shoulders of the Crackling Vanquisher
	tokenData[96700] = '' -- Shoulders of the Crackling Conqueror
	tokenData[96701] = '' -- Shoulders of the Crackling Protector
	tokenData[99667] = '' -- Gauntlets of the Cursed Protector
	tokenData[99668] = '' -- Shoulders of the Cursed Vanquisher
	tokenData[99669] = '' -- Shoulders of the Cursed Conqueror
	tokenData[99670] = '' -- Shoulders of the Cursed Protector
	tokenData[99671] = '' -- Helm of the Cursed Vanquisher
	tokenData[99672] = '' -- Helm of the Cursed Conqueror
	tokenData[99673] = '' -- Helm of the Cursed Protector
	tokenData[99674] = '' -- Leggings of the Cursed Vanquisher
	tokenData[99675] = '' -- Leggings of the Cursed Conqueror
	tokenData[99676] = '' -- Leggings of the Cursed Protector
	tokenData[99677] = '' -- Chest of the Cursed Vanquisher
	tokenData[99678] = '' -- Chest of the Cursed Conqueror
	tokenData[99679] = '' -- Chest of the Cursed Protector
	tokenData[99680] = '' -- Gauntlets of the Cursed Vanquisher
	tokenData[99681] = '' -- Gauntlets of the Cursed Conqueror
	tokenData[105860] = '' -- Essence of the Cursed Protector
	tokenData[105861] = '' -- Essence of the Cursed Conqueror
	tokenData[105862] = '' -- Essence of the Cursed Vanquisher
	tokenData[95569] = '' -- Chest of the Crackling Vanquisher
	tokenData[95570] = '' -- Gauntlets of the Crackling Vanquisher
	tokenData[95571] = '' -- Helm of the Crackling Vanquisher
	tokenData[95572] = '' -- Leggings of the Crackling Vanquisher
	tokenData[95573] = '' -- Shoulders of the Crackling Vanquisher
	tokenData[95574] = '' -- Chest of the Crackling Conqueror
	tokenData[95575] = '' -- Gauntlets of the Crackling Conqueror
	tokenData[95576] = '' -- Leggings of the Crackling Conqueror
	tokenData[95577] = '' -- Helm of the Crackling Conqueror
	tokenData[95578] = '' -- Shoulders of the Crackling Conqueror
	tokenData[95579] = '' -- Chest of the Crackling Protector
	tokenData[95580] = '' -- Gauntlets of the Crackling Protector
	tokenData[95581] = '' -- Leggings of the Crackling Protector
	tokenData[95582] = '' -- Helm of the Crackling Protector
	tokenData[95583] = '' -- Shoulders of the Crackling Protector
	tokenData[89249] = '' -- Chest of the Shadowy Vanquisher
	tokenData[89250] = '' -- Chest of the Shadowy Conqueror
	tokenData[89251] = '' -- Chest of the Shadowy Protector
	tokenData[89252] = '' -- Leggings of the Shadowy Vanquisher
	tokenData[89253] = '' -- Leggings of the Shadowy Conqueror
	tokenData[89254] = '' -- Leggings of the Shadowy Protector
	tokenData[89255] = '' -- Gauntlets of the Shadowy Vanquisher
	tokenData[89256] = '' -- Gauntlets of the Shadowy Conqueror
	tokenData[89257] = '' -- Gauntlets of the Shadowy Protector
	tokenData[89258] = '' -- Helm of the Shadowy Vanquisher
	tokenData[89259] = '' -- Helm of the Shadowy Conqueror
	tokenData[89260] = '' -- Helm of the Shadowy Protector
	tokenData[89261] = '' -- Shoulders of the Shadowy Vanquisher
	tokenData[89262] = '' -- Shoulders of the Shadowy Conqueror
	tokenData[89263] = '' -- Shoulders of the Shadowy Protector
	tokenData[95822] = '' -- Chest of the Crackling Vanquisher
	tokenData[95823] = '' -- Chest of the Crackling Conqueror
	tokenData[95824] = '' -- Chest of the Crackling Protector
	tokenData[95855] = '' -- Gauntlets of the Crackling Vanquisher
	tokenData[95856] = '' -- Gauntlets of the Crackling Conqueror
	tokenData[95857] = '' -- Gauntlets of the Crackling Protector
	tokenData[95879] = '' -- Helm of the Crackling Vanquisher
	tokenData[95880] = '' -- Helm of the Crackling Conqueror
	tokenData[95881] = '' -- Helm of the Crackling Protector
	tokenData[95887] = '' -- Leggings of the Crackling Vanquisher
	tokenData[95888] = '' -- Leggings of the Crackling Conqueror
	tokenData[95889] = '' -- Leggings of the Crackling Protector
	tokenData[95955] = '' -- Shoulders of the Crackling Vanquisher
	tokenData[95956] = '' -- Shoulders of the Crackling Conqueror
	tokenData[95957] = '' -- Shoulders of the Crackling Protector
	tokenData[89234] = '' -- Helm of the Shadowy Vanquisher
	tokenData[89235] = '' -- Helm of the Shadowy Conqueror
	tokenData[89236] = '' -- Helm of the Shadowy Protector
	tokenData[89237] = '' -- Chest of the Shadowy Conqueror
	tokenData[89238] = '' -- Chest of the Shadowy Protector
	tokenData[89239] = '' -- Chest of the Shadowy Vanquisher
	tokenData[89240] = '' -- Gauntlets of the Shadowy Conqueror
	tokenData[89241] = '' -- Gauntlets of the Shadowy Protector
	tokenData[89242] = '' -- Gauntlets of the Shadowy Vanquisher
	tokenData[89243] = '' -- Leggings of the Shadowy Conqueror
	tokenData[89244] = '' -- Leggings of the Shadowy Protector
	tokenData[89245] = '' -- Leggings of the Shadowy Vanquisher
	tokenData[89246] = '' -- Shoulders of the Shadowy Conqueror
	tokenData[89247] = '' -- Shoulders of the Shadowy Protector
	tokenData[89248] = '' -- Shoulders of the Shadowy Vanquisher
	tokenData[89264] = '' -- Chest of the Shadowy Vanquisher
	tokenData[89265] = '' -- Chest of the Shadowy Conqueror
	tokenData[89266] = '' -- Chest of the Shadowy Protector
	tokenData[89267] = '' -- Leggings of the Shadowy Vanquisher
	tokenData[89268] = '' -- Leggings of the Shadowy Conqueror
	tokenData[89269] = '' -- Leggings of the Shadowy Protector
	tokenData[89270] = '' -- Gauntlets of the Shadowy Vanquisher
	tokenData[89271] = '' -- Gauntlets of the Shadowy Conqueror
	tokenData[89272] = '' -- Gauntlets of the Shadowy Protector
	tokenData[89273] = '' -- Helm of the Shadowy Vanquisher
	tokenData[89274] = '' -- Helm of the Shadowy Conqueror
	tokenData[89275] = '' -- Helm of the Shadowy Protector
	tokenData[89276] = '' -- Shoulders of the Shadowy Vanquisher
	tokenData[89277] = '' -- Shoulders of the Shadowy Conqueror
	tokenData[89278] = '' -- Shoulders of the Shadowy Protector
	tokenData[78847] = '' -- Chest of the Corrupted Conqueror
	tokenData[78848] = '' -- Chest of the Corrupted Protector
	tokenData[78849] = '' -- Chest of the Corrupted Vanquisher
	tokenData[78850] = '' -- Crown of the Corrupted Conqueror
	tokenData[78851] = '' -- Crown of the Corrupted Protector
	tokenData[78852] = '' -- Crown of the Corrupted Vanquisher
	tokenData[78853] = '' -- Gauntlets of the Corrupted Conqueror
	tokenData[78854] = '' -- Gauntlets of the Corrupted Protector
	tokenData[78855] = '' -- Gauntlets of the Corrupted Vanquisher
	tokenData[78856] = '' -- Leggings of the Corrupted Conqueror
	tokenData[78857] = '' -- Leggings of the Corrupted Protector
	tokenData[78858] = '' -- Leggings of the Corrupted Vanquisher
	tokenData[78859] = '' -- Shoulders of the Corrupted Conqueror
	tokenData[78860] = '' -- Shoulders of the Corrupted Protector
	tokenData[78861] = '' -- Shoulders of the Corrupted Vanquisher
	tokenData[78170] = '' -- Shoulders of the Corrupted Vanquisher
	tokenData[78171] = '' -- Leggings of the Corrupted Vanquisher
	tokenData[78172] = '' -- Crown of the Corrupted Vanquisher
	tokenData[78173] = '' -- Gauntlets of the Corrupted Vanquisher
	tokenData[78174] = '' -- Chest of the Corrupted Vanquisher
	tokenData[78175] = '' -- Shoulders of the Corrupted Protector
	tokenData[78176] = '' -- Leggings of the Corrupted Protector
	tokenData[78177] = '' -- Crown of the Corrupted Protector
	tokenData[78178] = '' -- Gauntlets of the Corrupted Protector
	tokenData[78179] = '' -- Chest of the Corrupted Protector
	tokenData[78180] = '' -- Shoulders of the Corrupted Conqueror
	tokenData[78181] = '' -- Leggings of the Corrupted Conqueror
	tokenData[78182] = '' -- Crown of the Corrupted Conqueror
	tokenData[78183] = '' -- Gauntlets of the Corrupted Conqueror
	tokenData[78184] = '' -- Chest of the Corrupted Conqueror
	tokenData[71669] = '' -- Gauntlets of the Fiery Vanquisher
	tokenData[71670] = '' -- Crown of the Fiery Vanquisher
	tokenData[71671] = '' -- Leggings of the Fiery Vanquisher
	tokenData[71672] = '' -- Chest of the Fiery Vanquisher
	tokenData[71673] = '' -- Shoulders of the Fiery Vanquisher
	tokenData[71676] = '' -- Gauntlets of the Fiery Conqueror
	tokenData[71677] = '' -- Crown of the Fiery Conqueror
	tokenData[71678] = '' -- Leggings of the Fiery Conqueror
	tokenData[71679] = '' -- Chest of the Fiery Conqueror
	tokenData[71680] = '' -- Shoulders of the Fiery Conqueror
	tokenData[71683] = '' -- Gauntlets of the Fiery Protector
	tokenData[71684] = '' -- Crown of the Fiery Protector
	tokenData[71685] = '' -- Leggings of the Fiery Protector
	tokenData[71686] = '' -- Chest of the Fiery Protector
	tokenData[71687] = '' -- Shoulders of the Fiery Protector
	tokenData[78862] = '' -- Chest of the Corrupted Vanquisher
	tokenData[78863] = '' -- Chest of the Corrupted Conqueror
	tokenData[78864] = '' -- Chest of the Corrupted Protector
	tokenData[78865] = '' -- Gauntlets of the Corrupted Vanquisher
	tokenData[78866] = '' -- Gauntlets of the Corrupted Conqueror
	tokenData[78867] = '' -- Gauntlets of the Corrupted Protector
	tokenData[78868] = '' -- Crown of the Corrupted Vanquisher
	tokenData[78869] = '' -- Crown of the Corrupted Conqueror
	tokenData[78870] = '' -- Crown of the Corrupted Protector
	tokenData[78871] = '' -- Leggings of the Corrupted Vanquisher
	tokenData[78872] = '' -- Leggings of the Corrupted Conqueror
	tokenData[78873] = '' -- Leggings of the Corrupted Protector
	tokenData[78874] = '' -- Shoulders of the Corrupted Vanquisher
	tokenData[78875] = '' -- Shoulders of the Corrupted Conqueror
	tokenData[78876] = '' -- Shoulders of the Corrupted Protector
	tokenData[71668] = '' -- Helm of the Fiery Vanquisher
	tokenData[71674] = '' -- Mantle of the Fiery Vanquisher
	tokenData[71675] = '' -- Helm of the Fiery Conqueror
	tokenData[71681] = '' -- Mantle of the Fiery Conqueror
	tokenData[71682] = '' -- Helm of the Fiery Protector
	tokenData[71688] = '' -- Mantle of the Fiery Protector
	tokenData[119305] = '' -- Chest of the Iron Conqueror
	tokenData[119306] = '' -- Gauntlets of the Iron Conqueror
	tokenData[119307] = '' -- Leggings of the Iron Conqueror
	tokenData[119308] = '' -- Helm of the Iron Conqueror
	tokenData[119309] = '' -- Shoulders of the Iron Conqueror
	tokenData[119311] = '' -- Gauntlets of the Iron Vanquisher
	tokenData[119312] = '' -- Helm of the Iron Vanquisher
	tokenData[119313] = '' -- Leggings of the Iron Vanquisher
	tokenData[119314] = '' -- Shoulders of the Iron Vanquisher
	tokenData[119315] = '' -- Chest of the Iron Vanquisher
	tokenData[119318] = '' -- Chest of the Iron Protector
	tokenData[119319] = '' -- Gauntlets of the Iron Protector
	tokenData[119320] = '' -- Leggings of the Iron Protector
	tokenData[119321] = '' -- Helm of the Iron Protector
	tokenData[120151] = '' -- Gleaming Ashmaul Strongbox
	tokenData[120212] = '' -- Chest of the Iron Conqueror
	tokenData[120213] = '' -- Gauntlets of the Iron Conqueror
	tokenData[120214] = '' -- Leggings of the Iron Conqueror
	tokenData[120215] = '' -- Helm of the Iron Conqueror
	tokenData[120216] = '' -- Shoulders of the Iron Conqueror
	tokenData[120217] = '' -- Gauntlets of the Iron Vanquisher
	tokenData[120218] = '' -- Helm of the Iron Vanquisher
	tokenData[120219] = '' -- Leggings of the Iron Vanquisher
	tokenData[120220] = '' -- Shoulders of the Iron Vanquisher
	tokenData[120221] = '' -- Chest of the Iron Vanquisher
	tokenData[120222] = '' -- Chest of the Iron Protector
	tokenData[120223] = '' -- Gauntlets of the Iron Protector
	tokenData[120224] = '' -- Leggings of the Iron Protector
	tokenData[120225] = '' -- Helm of the Iron Protector
	tokenData[120226] = '' -- Shoulders of the Iron Protector
	tokenData[120227] = '' -- Chest of the Iron Conqueror
	tokenData[120228] = '' -- Gauntlets of the Iron Conqueror
	tokenData[120229] = '' -- Leggings of the Iron Conqueror
	tokenData[120230] = '' -- Helm of the Iron Conqueror
	tokenData[120231] = '' -- Shoulders of the Iron Conqueror
	tokenData[120232] = '' -- Gauntlets of the Iron Vanquisher
	tokenData[120233] = '' -- Helm of the Iron Vanquisher
	tokenData[120234] = '' -- Leggings of the Iron Vanquisher
	tokenData[120235] = '' -- Shoulders of the Iron Vanquisher
	tokenData[120236] = '' -- Chest of the Iron Vanquisher
	tokenData[120237] = '' -- Chest of the Iron Protector
	tokenData[120238] = '' -- Gauntlets of the Iron Protector
	tokenData[120239] = '' -- Leggings of the Iron Protector
	tokenData[120240] = '' -- Helm of the Iron Protector
	tokenData[120241] = '' -- Shoulders of the Iron Protector
	tokenData[120242] = '' -- Chest of the Iron Conqueror
	tokenData[120243] = '' -- Gauntlets of the Iron Conqueror
	tokenData[120244] = '' -- Leggings of the Iron Conqueror
	tokenData[120245] = '' -- Helm of the Iron Conqueror
	tokenData[120246] = '' -- Shoulders of the Iron Conqueror
	tokenData[120247] = '' -- Gauntlets of the Iron Vanquisher
	tokenData[120248] = '' -- Helm of the Iron Vanquisher
	tokenData[120249] = '' -- Leggings of the Iron Vanquisher
	tokenData[120250] = '' -- Shoulders of the Iron Vanquisher
	tokenData[120251] = '' -- Chest of the Iron Vanquisher
	tokenData[120252] = '' -- Chest of the Iron Protector
	tokenData[120253] = '' -- Gauntlets of the Iron Protector
	tokenData[120254] = '' -- Leggings of the Iron Protector
	tokenData[120255] = '' -- Helm of the Iron Protector
	tokenData[120256] = '' -- Shoulders of the Iron Protector
	tokenData[63682] = '' -- Helm of the Forlorn Vanquisher
	tokenData[63683] = '' -- Helm of the Forlorn Conqueror
	tokenData[63684] = '' -- Helm of the Forlorn Protector
	tokenData[64314] = '' -- Mantle of the Forlorn Vanquisher
	tokenData[64315] = '' -- Mantle of the Forlorn Conqueror
	tokenData[64316] = '' -- Mantle of the Forlorn Protector
	tokenData[65000] = '' -- Crown of the Forlorn Protector
	tokenData[65001] = '' -- Crown of the Forlorn Conqueror
	tokenData[65002] = '' -- Crown of the Forlorn Vanquisher
	tokenData[65087] = '' -- Shoulders of the Forlorn Protector
	tokenData[65088] = '' -- Shoulders of the Forlorn Conqueror
	tokenData[65089] = '' -- Shoulders of the Forlorn Vanquisher
	tokenData[66998] = '' -- Essence of the Forlorn
	tokenData[67423] = '' -- Chest of the Forlorn Conqueror
	tokenData[67424] = '' -- Chest of the Forlorn Protector
	tokenData[67425] = '' -- Chest of the Forlorn Vanquisher
	tokenData[67426] = '' -- Leggings of the Forlorn Vanquisher
	tokenData[67427] = '' -- Leggings of the Forlorn Protector
	tokenData[67428] = '' -- Leggings of the Forlorn Conqueror
	tokenData[67429] = '' -- Gauntlets of the Forlorn Conqueror
	tokenData[67430] = '' -- Gauntlets of the Forlorn Protector
	tokenData[67431] = '' -- Gauntlets of the Forlorn Vanquisher
	tokenData[40610] = '' -- Chestguard of the Lost Conqueror
	tokenData[40611] = '' -- Chestguard of the Lost Protector
	tokenData[40612] = '' -- Chestguard of the Lost Vanquisher
	tokenData[40613] = '' -- Gloves of the Lost Conqueror
	tokenData[40614] = '' -- Gloves of the Lost Protector
	tokenData[40615] = '' -- Gloves of the Lost Vanquisher
	tokenData[40616] = '' -- Helm of the Lost Conqueror
	tokenData[40617] = '' -- Helm of the Lost Protector
	tokenData[40618] = '' -- Helm of the Lost Vanquisher
	tokenData[40619] = '' -- Leggings of the Lost Conqueror
	tokenData[40620] = '' -- Leggings of the Lost Protector
	tokenData[40621] = '' -- Leggings of the Lost Vanquisher
	tokenData[40622] = '' -- Spaulders of the Lost Conqueror
	tokenData[40623] = '' -- Spaulders of the Lost Protector
	tokenData[40624] = '' -- Spaulders of the Lost Vanquisher
	tokenData[40625] = '' -- Breastplate of the Lost Conqueror
	tokenData[40626] = '' -- Breastplate of the Lost Protector
	tokenData[40627] = '' -- Breastplate of the Lost Vanquisher
	tokenData[40628] = '' -- Gauntlets of the Lost Conqueror
	tokenData[40629] = '' -- Gauntlets of the Lost Protector
	tokenData[40630] = '' -- Gauntlets of the Lost Vanquisher
	tokenData[40631] = '' -- Crown of the Lost Conqueror
	tokenData[40632] = '' -- Crown of the Lost Protector
	tokenData[40633] = '' -- Crown of the Lost Vanquisher
	tokenData[40634] = '' -- Legplates of the Lost Conqueror
	tokenData[40635] = '' -- Legplates of the Lost Protector
	tokenData[40636] = '' -- Legplates of the Lost Vanquisher
	tokenData[40637] = '' -- Mantle of the Lost Conqueror
	tokenData[40638] = '' -- Mantle of the Lost Protector
	tokenData[40639] = '' -- Mantle of the Lost Vanquisher
	tokenData[45632] = '' -- Breastplate of the Wayward Conqueror
	tokenData[45633] = '' -- Breastplate of the Wayward Protector
	tokenData[45634] = '' -- Breastplate of the Wayward Vanquisher
	tokenData[45635] = '' -- Chestguard of the Wayward Conqueror
	tokenData[45636] = '' -- Chestguard of the Wayward Protector
	tokenData[45637] = '' -- Chestguard of the Wayward Vanquisher
	tokenData[45638] = '' -- Crown of the Wayward Conqueror
	tokenData[45639] = '' -- Crown of the Wayward Protector
	tokenData[45640] = '' -- Crown of the Wayward Vanquisher
	tokenData[45641] = '' -- Gauntlets of the Wayward Conqueror
	tokenData[45642] = '' -- Gauntlets of the Wayward Protector
	tokenData[45643] = '' -- Gauntlets of the Wayward Vanquisher
	tokenData[45644] = '' -- Gloves of the Wayward Conqueror
	tokenData[45645] = '' -- Gloves of the Wayward Protector
	tokenData[45646] = '' -- Gloves of the Wayward Vanquisher
	tokenData[45647] = '' -- Helm of the Wayward Conqueror
	tokenData[45648] = '' -- Helm of the Wayward Protector
	tokenData[45649] = '' -- Helm of the Wayward Vanquisher
	tokenData[45650] = '' -- Leggings of the Wayward Conqueror
	tokenData[45651] = '' -- Leggings of the Wayward Protector
	tokenData[45652] = '' -- Leggings of the Wayward Vanquisher
	tokenData[45653] = '' -- Legplates of the Wayward Conqueror
	tokenData[45654] = '' -- Legplates of the Wayward Protector
	tokenData[45655] = '' -- Legplates of the Wayward Vanquisher
	tokenData[45656] = '' -- Mantle of the Wayward Conqueror
	tokenData[45657] = '' -- Mantle of the Wayward Protector
	tokenData[45658] = '' -- Mantle of the Wayward Vanquisher
	tokenData[45659] = '' -- Spaulders of the Wayward Conqueror
	tokenData[45660] = '' -- Spaulders of the Wayward Protector
	tokenData[45661] = '' -- Spaulders of the Wayward Vanquisher
	tokenData[47242] = '' -- Trophy of the Crusade
	tokenData[47557] = '' -- Regalia of the Grand Conqueror
	tokenData[47558] = '' -- Regalia of the Grand Protector
	tokenData[47559] = '' -- Regalia of the Grand Vanquisher
	tokenData[52025] = '' -- Vanquisher's Mark of Sanctification
	tokenData[52026] = '' -- Protector's Mark of Sanctification
	tokenData[52027] = '' -- Conqueror's Mark of Sanctification
	tokenData[52028] = '' -- Vanquisher's Mark of Sanctification};
	tokenData[52029] = '' -- Protector's Mark of Sanctification
	tokenData[52030] = '' -- Conqueror's Mark of Sanctification
	tokenData[29753] = '' -- Chestguard of the Fallen Defender
	tokenData[29754] = '' -- Chestguard of the Fallen Champion
	tokenData[29755] = '' -- Chestguard of the Fallen Hero
	tokenData[29756] = '' -- Gloves of the Fallen Hero
	tokenData[29757] = '' -- Gloves of the Fallen Champion
	tokenData[29758] = '' -- Gloves of the Fallen Defender
	tokenData[29759] = '' -- Helm of the Fallen Hero
	tokenData[29760] = '' -- Helm of the Fallen Champion
	tokenData[29761] = '' -- Helm of the Fallen Defender
	tokenData[29762] = '' -- Pauldrons of the Fallen Hero
	tokenData[29763] = '' -- Pauldrons of the Fallen Champion
	tokenData[29764] = '' -- Pauldrons of the Fallen Defender
	tokenData[29765] = '' -- Leggings of the Fallen Hero
	tokenData[29766] = '' -- Leggings of the Fallen Champion
	tokenData[29767] = '' -- Leggings of the Fallen Defender
	tokenData[30236] = '' -- Chestguard of the Vanquished Champion
	tokenData[30237] = '' -- Chestguard of the Vanquished Defender
	tokenData[30238] = '' -- Chestguard of the Vanquished Hero
	tokenData[30239] = '' -- Gloves of the Vanquished Champion
	tokenData[30240] = '' -- Gloves of the Vanquished Defender
	tokenData[30241] = '' -- Gloves of the Vanquished Hero
	tokenData[30242] = '' -- Helm of the Vanquished Champion
	tokenData[30243] = '' -- Helm of the Vanquished Defender
	tokenData[30244] = '' -- Helm of the Vanquished Hero
	tokenData[30245] = '' -- Leggings of the Vanquished Champion
	tokenData[30246] = '' -- Leggings of the Vanquished Defender
	tokenData[30247] = '' -- Leggings of the Vanquished Hero
	tokenData[30248] = '' -- Pauldrons of the Vanquished Champion
	tokenData[30249] = '' -- Pauldrons of the Vanquished Defender
	tokenData[30250] = '' -- Pauldrons of the Vanquished Hero
	tokenData[31089] = '' -- Chestguard of the Forgotten Conqueror
	tokenData[31090] = '' -- Chestguard of the Forgotten Vanquisher
	tokenData[31091] = '' -- Chestguard of the Forgotten Protector
	tokenData[31092] = '' -- Gloves of the Forgotten Conqueror
	tokenData[31093] = '' -- Gloves of the Forgotten Vanquisher
	tokenData[31094] = '' -- Gloves of the Forgotten Protector
	tokenData[31095] = '' -- Helm of the Forgotten Protector
	tokenData[31096] = '' -- Helm of the Forgotten Vanquisher
	tokenData[31097] = '' -- Helm of the Forgotten Conqueror
	tokenData[31098] = '' -- Leggings of the Forgotten Conqueror
	tokenData[31099] = '' -- Leggings of the Forgotten Vanquisher
	tokenData[31100] = '' -- Leggings of the Forgotten Protector
	tokenData[31101] = '' -- Pauldrons of the Forgotten Conqueror
	tokenData[31102] = '' -- Pauldrons of the Forgotten Vanquisher
	tokenData[31103] = '' -- Pauldrons of the Forgotten Protector
	tokenData[34848] = '' -- Bracers of the Forgotten Conqueror
	tokenData[34851] = '' -- Bracers of the Forgotten Protector
	tokenData[34852] = '' -- Bracers of the Forgotten Vanquisher
	tokenData[34853] = '' -- Belt of the Forgotten Conqueror
	tokenData[34854] = '' -- Belt of the Forgotten Protector
	tokenData[34855] = '' -- Belt of the Forgotten Vanquisher
	tokenData[34856] = '' -- Boots of the Forgotten Conqueror
	tokenData[34857] = '' -- Boots of the Forgotten Protector
	tokenData[34858] = '' -- Boots of the Forgotten Vanquisher
	tokenData[22349] = '' -- Desecrated Breastplate
	tokenData[22350] = '' -- Desecrated Tunic
	tokenData[22351] = '' -- Desecrated Robe
	tokenData[22352] = '' -- Desecrated Legplates
	tokenData[22353] = '' -- Desecrated Helmet
	tokenData[22354] = '' -- Desecrated Pauldrons
	tokenData[22355] = '' -- Desecrated Bracers
	tokenData[22356] = '' -- Desecrated Waistguard
	tokenData[22357] = '' -- Desecrated Gauntlets
	tokenData[22358] = '' -- Desecrated Sabatons
	tokenData[22359] = '' -- Desecrated Legguards
	tokenData[22360] = '' -- Desecrated Headpiece
	tokenData[22361] = '' -- Desecrated Spaulders
	tokenData[22362] = '' -- Desecrated Wristguards
	tokenData[22363] = '' -- Desecrated Girdle
	tokenData[22364] = '' -- Desecrated Handguards
	tokenData[22365] = '' -- Desecrated Boots
	tokenData[22366] = '' -- Desecrated Leggings
	tokenData[22367] = '' -- Desecrated Circlet
	tokenData[22368] = '' -- Desecrated Shoulderpads
	tokenData[22369] = '' -- Desecrated Bindings
	tokenData[22370] = '' -- Desecrated Belt
	tokenData[22371] = '' -- Desecrated Gloves
	tokenData[22372] = '' -- Desecrated Sandals

	tokenData[114082] = '' -- Grandiose Bracers
	tokenData[114083] = '' -- Grandiose Robes
	tokenData[114084] = '' -- Grandiose Treads
	tokenData[114085] = '' -- Grandiose Spaulders
	tokenData[114086] = '' -- Grandiose Choker
	tokenData[114087] = '' -- Grandiose Trinket
	tokenData[114112] = '' -- Grandiose Armament
	tokenData[119114] = '' -- Grandiose Gauntlets
	tokenData[119116] = '' -- Grandiose Hood
	tokenData[119118] = '' -- Grandiose Leggings
	tokenData[119120] = '' -- Grandiose Girdle
	tokenData[119122] = '' -- Grandiose Ring
	tokenData[119124] = '' -- Grandiose Cloak
	tokenData[114069] = '' -- Turbulent Bracers
	tokenData[114070] = '' -- Turbulent Robes
	tokenData[114071] = '' -- Turbulent Treads
	tokenData[114072] = '' -- Turbulent Gauntlets
	tokenData[114073] = '' -- Turbulent Hood
	tokenData[114074] = '' -- Turbulent Leggings
	tokenData[114075] = '' -- Turbulent Spaulders
	tokenData[114076] = '' -- Turbulent Girdle
	tokenData[114077] = '' -- Turbulent Ring
	tokenData[114078] = '' -- Turbulent Choker
	tokenData[114079] = '' -- Turbulent Cloak
	tokenData[114080] = '' -- Turbulent Trinket
	tokenData[114110] = '' -- Turbulent Armament
	tokenData[114057] = '' -- Munificent Bracers
	tokenData[114058] = '' -- Munificent Robes
	tokenData[114059] = 'INVTYPE_FEET' -- Munificent Treads
	tokenData[114060] = '' -- Munificent Gauntlets
	tokenData[114061] = '' -- Munificent Hood
	tokenData[114062] = '' -- Munificent Leggings
	tokenData[114063] = '' -- Munificent Spaulders
	tokenData[114064] = '' -- Munificent Girdle
	tokenData[114065] = '' -- Munificent Ring
	tokenData[114066] = '' -- Munificent Choker
	tokenData[114067] = '' -- Munificent Cloak
	tokenData[114068] = '' -- Munificent Trinket
	tokenData[114109] = '' -- Munificent Armament
	tokenData[114100] = '' -- Tormented Spaulders
	tokenData[114105] = '' -- Tormented Trinket
	tokenData[114097] = '' -- Tormented Gauntlets
	tokenData[114099] = '' -- Tormented Leggings
	tokenData[114094] = 'INVTYPE_WRIST,,114310,114311,114312,114313,' -- Tormented Bracers
	tokenData[114108] = '' -- Tormented Armament
	tokenData[114096] = '' -- Tormented Treads
	tokenData[114098] = '' -- Tormented Hood
	tokenData[103982] = '' -- Burden of Eternity
	tokenData[114101] = '' -- Tormented Girdle
	tokenData[114052] = '' -- Gleaming Ring
	tokenData[114053] = '' -- Shimmering Gauntlets
	tokenData[102263] = '' -- Timeless Plate Chestpiece
	tokenData[102264] = '' -- Timeless Plate Boots
	tokenData[102265] = '' -- Timeless Plate Gloves
	tokenData[102266] = '' -- Timeless Plate Helm
	tokenData[102267] = '' -- Timeless Plate Leggings
	tokenData[102268] = '' -- Timeless Plate Spaulders
	tokenData[102269] = '' -- Timeless Plate Belt
	tokenData[102270] = '' -- Timeless Mail Chestpiece
	tokenData[102271] = '' -- Timeless Mail Boots
	tokenData[102272] = '' -- Timeless Mail Gloves
	tokenData[102273] = '' -- Timeless Mail Helm
	tokenData[102274] = '' -- Timeless Mail Leggings
	tokenData[102275] = '' -- Timeless Mail Spaulders
	tokenData[102276] = '' -- Timeless Mail Belt
	tokenData[102277] = '' -- Timeless Leather Chestpiece
	tokenData[102278] = '' -- Timeless Leather Boots
	tokenData[102279] = '' -- Timeless Leather Gloves
	tokenData[102280] = '' -- Timeless Leather Helm
	tokenData[102281] = '' -- Timeless Leather Leggings
	tokenData[102282] = '' -- Timeless Leather Spaulders
	tokenData[102283] = '' -- Timeless Leather Belt
	tokenData[102284] = '' -- Timeless Cloth Robes
	tokenData[102285] = '' -- Timeless Cloth Boots
	tokenData[102286] = '' -- Timeless Cloth Gloves
	tokenData[102287] = '' -- Timeless Cloth Helm
	tokenData[102288] = '' -- Timeless Cloth Leggings
	tokenData[102289] = '' -- Timeless Cloth Spaulders
	tokenData[102290] = '' -- Timeless Cloth Belt
	tokenData[102291] = '' -- Timeless Signet
	tokenData[102318] = '' -- Timeless Cloak
	tokenData[102320] = '' -- Timeless Plate Bracers
	tokenData[102321] = '' -- Timeless Cloth Bracers
	tokenData[102322] = '' -- Timeless Leather Bracers
	tokenData[102323] = '' -- Timeless Mail Bracers
	tokenData[104345] = '' -- Timeless Lavalliere
	tokenData[104347] = '' -- Timeless Curio
	tokenData[97826] = '' -- Latent Kor'kron Chestpiece
	tokenData[97827] = '' -- Latent Kor'kron Boots
	tokenData[97828] = '' -- Latent Kor'kron Gloves
	tokenData[97829] = '' -- Latent Kor'kron Helm
	tokenData[97830] = '' -- Latent Kor'kron Leggings
	tokenData[97831] = '' -- Latent Kor'kron Spaulders
	tokenData[97832] = '' -- Latent Kor'kron Belt
end
